language: python
install: pip install tox
script: tox -v -e $TOX_ENV -- --verbose
sudo: false
env:
  - TOX_ENV=py26pep8
  - TOX_ENV=py26-coverage
  - TOX_ENV=py26
notifications:
  email:
    - development@policystat.com
