# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py37pep8, py37, py37-coverage

[testenv]
commands =
  nosetests --with-doctest []
deps =
  -r{toxinidir}/requirements/testing.txt

# Coverage for python 3.7
[testenv:py37-coverage]
commands =
  nosetests --with-doctest --with-coverage --cover-package htmltreediff []

[testenv:py37pep8]
basepython = python3.7
deps = flake8
commands = flake8 htmltreediff

[flake8]
select = E,W,F
max-line-length = 95
